[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ece608.toposort"
description = ''
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = [
  "Topologocal Sort",
  "Graphs",
  "Directed Acyclc Graphs",
  "Depth First Search",
  "Kahn's Algorithm",
  "Breadth First Search",
  "Algorithms",
  "DAG",
  "Dynamic DAG",
]
authors = [
  { name = "Santosh Ahuja", email = "ahuja28@purdue.edu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/suntosh/ECE608/#ReadMe"
Issues = "https://github.com/suntosh/ECE608/issues"
Source = "https://github.com/suntosh/ECE608"

[tool.hatch.version]
path = "ece608/toposort/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
  "networkx",
  "matplotlib"  
]


[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=ece608/toposort --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "ece608/toposort/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
